apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-java-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-java-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
